# Generated by Django 4.0.4 on 2022-04-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='14.04.2022')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('distance', models.IntegerField()),
            ],
        ),
    ]
